service: routine-finder-service
runtime: java11
env: standard
instance_class: F2
handlers:
  - url: .*
    script: auto
env_variables:
  GCP_SECRETS_ENABLED: 'False'
  SPRING_PROFILES_ACTIVE: uat
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: nimble-equator-282207@appspot.gserviceaccount.com
